Multiple address addition & selection at checkout
Moxie-Labs/home-appetit-hydrogen pull request #102
Opened 2022-11-29 13:33 UTC by SidPainter

This PR adds the functionality of selecting from a list of saved addresses for a logged in user. 
Added 'Add New Address' button as well to add new address from the checkout screen itself.

2022-12-01 05:51 UTC, JPTrey91 requested changes

2022-12-01 05:51 UTC, JPTrey91 commented on src/components/DeliveryInfo.client.jsx
> +    const onClickSubmit = async (event) => {
Adding new address causes the page to reload unnecessarily.

2022-12-01 11:01 UTC, SidPainter commented on src/components/DeliveryInfo.client.jsx
> +    const onClickSubmit = async (event) => {
Removed keywords.

2022-12-05 18:55 UTC, JPTrey91 approved these changes

2022-12-05 18:55 UTC, merged