autofill delivery details at checkout
Moxie-Labs/home-appetit-hydrogen pull request #41
Opened 2022-10-19 11:50 UTC by SidPainter

2022-10-20 03:34 UTC, JPTrey91 requested changes

2022-10-20 03:34 UTC, JPTrey91 commented on src/components/OrderSection.client.jsx
>      let [deliveryState, setDeliveryState] = useState(isGuest ? null : "Pennsylvania");
This should not be using hardcoded values.

2022-10-20 06:51 UTC, SidPainter commented on src/components/OrderSection.client.jsx
>      let [deliveryState, setDeliveryState] = useState(isGuest ? null : "Pennsylvania");
I have approved your changes on that PR. But yours are on feature/accounts and this is feature/ordering. I have seen the changes that you are talking about but how to incorporate them here.

2022-10-25 20:51 UTC, JPTrey91 commented on src/components/OrderSection.client.jsx
> +    let [country, setCountry] = useState(isGuest ? null : "United States");
This will always be "United States", and setting it to `null` for guests will cause it to fail.

2022-10-25 20:52 UTC, JPTrey91 approved these changes

2022-10-25 20:52 UTC, merged