More Responsive Fix and Style Updates
Moxie-Labs/home-appetit-hydrogen pull request #56
Opened 2022-10-27 18:35 UTC by francepastrana

2022-10-31 18:15 UTC, JPTrey91 requested changes
OrderSummary is misaligned when simulating an iPhone 14 Pro.

<img width="505" alt="Screen Shot 2022-10-31 at 2 14 27 PM" src="https://user-images.githubusercontent.com/22353673/199080126-5776efed-ba6c-47d4-aee2-b41c9d0bb24c.png">

2022-10-31 18:15 UTC, JPTrey91 commented on src/styles/OrderSummary.css
> +    width: 87%;
If we're going to use percentages, we should also have `min` and `max-width` set.

2022-11-02 15:36 UTC, JPTrey91 approved these changes

2022-11-02 15:40 UTC, JPTrey91 requested changes
Still seeing visual issues: 
<img width="418" alt="Screen Shot 2022-11-02 at 11 38 47 AM" src="https://user-images.githubusercontent.com/22353673/199533984-75db62fa-578a-4a36-94bf-07694ff53ecb.png">

2022-11-03 11:49 UTC, francepastrana commented
> Still seeing visual issues: <img alt="Screen Shot 2022-11-02 at 11 38 47 AM" width="418" src="https://user-images.githubusercontent.com/22353673/199533984-75db62fa-578a-4a36-94bf-07694ff53ecb.png">

![image](https://user-images.githubusercontent.com/63346912/199713102-29c4f3bb-af0a-47dc-8e19-9835d77f7f0a.png)

Floating order summary and header display condition fixed

2022-11-03 14:45 UTC, JPTrey91 commented
Still seeing too many visual inconsistencies to approve this.  Please revise: 

<img width="663" alt="Screen Shot 2022-11-03 at 10 42 53 AM" src="https://user-images.githubusercontent.com/22353673/199752277-1ba94934-d476-4c95-94ba-61b111080cd9.png">

<img width="426" alt="Screen Shot 2022-11-03 at 10 44 42 AM" src="https://user-images.githubusercontent.com/22353673/199752536-d775b803-3eb2-446d-bd56-6c37d4737eeb.png">

<img width="478" alt="Screen Shot 2022-11-03 at 10 44 47 AM" src="https://user-images.githubusercontent.com/22353673/199752571-6ee8c528-67da-4b11-a06b-e371f58537bc.png">

<img width="585" alt="Screen Shot 2022-11-03 at 10 45 02 AM" src="https://user-images.githubusercontent.com/22353673/199752597-083c24bd-c85c-4174-b25b-817d3296552f.png">

2022-11-04 12:03 UTC, francepastrana commented
@JPTrey91 Weird. Dish card modals on mobile is already fixed. Something is not right here. Anyway I re-fixed it again and added style elements to match figma.

2022-11-09 19:52 UTC, JPTrey91 approved these changes

2022-11-09 19:52 UTC, merged