Jsimonelli/tu450 gift card variants
Moxie-Labs/home-appetit-hydrogen pull request #75
Opened 2022-11-10 23:31 UTC by JPTrey91

This branch implements behavior on the Gift Card page, including:

* form validation
* connecting calculator value to form
* zipcode checker
* connects appropriate product/variant to selected choice
* enables checkout

2022-11-11 10:35 UTC, SidPainter requested changes

2022-11-11 10:35 UTC, SidPainter commented on src/routes/order/index.server.jsx
> -  CacheNone,
This is breaking order now section when user is logged in and clicks on Order Now button from My Account page it gives Uncaught ReferenceError: CacheNone is not defined. Please fix it.

2022-11-11 17:21 UTC, JPTrey91 commented on src/routes/order/index.server.jsx
> -  CacheNone,
Updated.

2022-11-12 05:57 UTC, SidPainter approved these changes

2022-11-14 20:46 UTC, merged